# Generated by Django 4.0 on 2021-12-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscador',
            name='primer_busqueda',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='buscador',
            name='ultima_busqueda',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='buscador',
            name='ultimos_resultados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
